[package]
name = "adder-proc-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3"
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
